Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
# 根据实际情况更改
Database:
  DBType: mysql
  UserName: root
  Password: Joe5323
  Host: 127.0.0.1:3306
  DBName: service-template
  TablePrefix: st_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
App:
  DefaultContextTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8080/file/static
  UploadImageMaxSize: 5  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
  UploadDocAllowExts:
    - .pdf
    - .docx
    - .doc
    - .txt
    - .xls
    - .xlsx
    - .ppt
    - .pptx
  UploadOtherMaxSize: 50 # MB
# 根据实际情况更改
JWT:
  Secret: your_real_secret
  Issuer: your_real_issuer
  Expire: 7200 # seconds
  SessionSecretLogin: use_2_login_session
